site_name: WordNet Porter
site_description: A utility to migrate WordNet SQLite database to PostgreSQL
site_author: onareach
repo_url: https://github.com/onareach/wordnet-porter
repo_name: onareach/wordnet-porter

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Development: development.md
  - API Reference: api_reference.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
