name: Basic CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.10']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: System information
      run: |
        echo "Operating system: $(uname -a)"
        echo "GitHub workspace: $GITHUB_WORKSPACE"
        echo "Python location: $(which python)"
        python --version
    
    - name: Create virtual environment
      run: |
        python -m venv venv
        echo "Created virtual environment"
        source venv/bin/activate
        echo "Activated virtual environment"
        echo "Python path: $(which python)"
        python --version
    
    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install psycopg2-binary
        pip install -e .
        echo "Installed packages:"
        pip list
    
    - name: Test basic import
      run: |
        source venv/bin/activate
        python -c "import wordnet_porter; print(f'WordNet Porter version: {wordnet_porter.__version__}')"
    
    - name: Create dummy SQLite database
      run: |
        mkdir -p /tmp/wordnet
        touch /tmp/wordnet/wn.db
        echo "Created dummy SQLite database at /tmp/wordnet/wn.db"
    
    - name: Run basic test
      env:
        WORDNET_SQLITE_PATH: /tmp/wordnet/wn.db
      run: |
        source venv/bin/activate
        python -m pytest tests/test_basic.py -v
